### ISSUE TITLE
关于NGSIM数据集预处理的代码

### ISSUE THREAD

**Issue by ShqWW** [xincoder/GRIP#11]
你好， 可以提供一下NGSIM数据集预处理的代码吗？我想复现你论文中关于NGSIM数据集的结果。希望你百忙之中能提供一下NGSIM数据处理的一些细节。非常感谢。

**Comment by xincoder** [comment]
@ShengqiWang 你好。非常感谢你对我们工作的关注。关于NGSIM数据集，我直接使用conv-social-pool文章的code (https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)，以保证可以跟其他文章对比实验结果。另外，其他研究人员已经讨论了相关的问题，可以借鉴一下他们讨论的技巧（https://github.com/xincoder/GRIP/issues/9）。

**Comment by ShqWW** [comment]
> @ShengqiWang 你好。非常感谢你对我们工作的关注。关于NGSIM数据集，我直接使用conv-social-pool文章的code ([https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)，以保证可以跟其他文章对比实验结果。另外，其他研究人员已经讨论了相关的问题，可以借鉴一下他们讨论的技巧（https://github.com/xincoder/GRIP/issues/9）。](https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)%EF%BC%8C%E4%BB%A5%E4%BF%9D%E8%AF%81%E5%8F%AF%E4%BB%A5%E8%B7%9F%E5%85%B6%E4%BB%96%E6%96%87%E7%AB%A0%E5%AF%B9%E6%AF%94%E5%AE%9E%E9%AA%8C%E7%BB%93%E6%9E%9C%E3%80%82%E5%8F%A6%E5%A4%96%EF%BC%8C%E5%85%B6%E4%BB%96%E7%A0%94%E7%A9%B6%E4%BA%BA%E5%91%98%E5%B7%B2%E7%BB%8F%E8%AE%A8%E8%AE%BA%E4%BA%86%E7%9B%B8%E5%85%B3%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%80%9F%E9%89%B4%E4%B8%80%E4%B8%8B%E4%BB%96%E4%BB%AC%E8%AE%A8%E8%AE%BA%E7%9A%84%E6%8A%80%E5%B7%A7%EF%BC%88https://github.com/xincoder/GRIP/issues/9%EF%BC%89%E3%80%82)

那个预处理代码我看过 也用python重写过， 但不能直接套用你的模型。除了https://github.com/xincoder/GRIP/issues/9讨论的几个问题还包括：
1. 图是怎么建立的，比如距离小于多少阈值建立边

**Comment by chaosles** [comment]
如果自己处理数据，我建议你修改data_process.py中get_frame_instance_dict这个函数，处理方法是将你的数据处理成像now_dict一样格式的字典。即
{ frame: { vehicle: [ features ] } }
后面的函数主体不用改变，只需要微调其中的特征对应的索引位置。

**Comment by Patrickyc** [comment]
> 
> 
> > @ShengqiWang 你好。非常感谢你对我们工作的关注。关于NGSIM数据集，我直接使用conv-social-pool文章的code ([https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)，以保证可以跟其他文章对比实验结果。另外，其他研究人员已经讨论了相关的问题，可以借鉴一下他们讨论的技巧（https://github.com/xincoder/GRIP/issues/9）。](https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)%EF%BC%8C%E4%BB%A5%E4%BF%9D%E8%AF%81%E5%8F%AF%E4%BB%A5%E8%B7%9F%E5%85%B6%E4%BB%96%E6%96%87%E7%AB%A0%E5%AF%B9%E6%AF%94%E5%AE%9E%E9%AA%8C%E7%BB%93%E6%9E%9C%E3%80%82%E5%8F%A6%E5%A4%96%EF%BC%8C%E5%85%B6%E4%BB%96%E7%A0%94%E7%A9%B6%E4%BA%BA%E5%91%98%E5%B7%B2%E7%BB%8F%E8%AE%A8%E8%AE%BA%E4%BA%86%E7%9B%B8%E5%85%B3%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%80%9F%E9%89%B4%E4%B8%80%E4%B8%8B%E4%BB%96%E4%BB%AC%E8%AE%A8%E8%AE%BA%E7%9A%84%E6%8A%80%E5%B7%A7%EF%BC%88#9)
> 
> 那个预处理代码我看过 也用python重写过， 但不能直接套用你的模型。除了[https://github.com/xincoder/GRIP/issues/9讨论的几个问题还包括：](https://github.com/xincoder/GRIP/issues/9%E8%AE%A8%E8%AE%BA%E7%9A%84%E5%87%A0%E4%B8%AA%E9%97%AE%E9%A2%98%E8%BF%98%E5%8C%85%E6%8B%AC%EF%BC%9A)
> 
>     1. 图是怎么建立的，比如距离小于多少阈值建立边
阈值设定为 10 meter
![图片](https://user-images.githubusercontent.com/17465487/102215237-65845800-3f14-11eb-9890-861a7e0ce800.png) 
计算出 x 坐标之间的距离。
![图片](https://user-images.githubusercontent.com/17465487/102215386-98c6e700-3f14-11eb-80b1-ddadb7db792d.png)

**Comment by guoyage** [comment]
> > > @ShengqiWang 你好。非常感谢你对我们工作的关注。关于NGSIM数据集，我直接使用conv-social-pool文章的code ([https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)，以保证可以跟其他文章对比实验结果。另外，其他研究人员已经讨论了相关的问题，可以借鉴一下他们讨论的技巧（https://github.com/xincoder/GRIP/issues/9）。](https://github.com/nachiket92/conv-social-pooling/blob/master/preprocess_data.m)%EF%BC%8C%E4%BB%A5%E4%BF%9D%E8%AF%81%E5%8F%AF%E4%BB%A5%E8%B7%9F%E5%85%B6%E4%BB%96%E6%96%87%E7%AB%A0%E5%AF%B9%E6%AF%94%E5%AE%9E%E9%AA%8C%E7%BB%93%E6%9E%9C%E3%80%82%E5%8F%A6%E5%A4%96%EF%BC%8C%E5%85%B6%E4%BB%96%E7%A0%94%E7%A9%B6%E4%BA%BA%E5%91%98%E5%B7%B2%E7%BB%8F%E8%AE%A8%E8%AE%BA%E4%BA%86%E7%9B%B8%E5%85%B3%E7%9A%84%E9%97%AE%E9%A2%98%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%80%9F%E9%89%B4%E4%B8%80%E4%B8%8B%E4%BB%96%E4%BB%AC%E8%AE%A8%E8%AE%BA%E7%9A%84%E6%8A%80%E5%B7%A7%EF%BC%88#9)
> > 
> > 
> > 那个预处理代码我看过 也用python重写过， 但不能直接套用你的模型。除了[https://github.com/xincoder/GRIP/issues/9讨论的几个问题还包括：](https://github.com/xincoder/GRIP/issues/9%E8%AE%A8%E8%AE%BA%E7%9A%84%E5%87%A0%E4%B8%AA%E9%97%AE%E9%A2%98%E8%BF%98%E5%8C%85%E6%8B%AC%EF%BC%9A)
> > ```
> > 1. 图是怎么建立的，比如距离小于多少阈值建立边
> > ```
> 
> 阈值设定为 10 meter
> ![图片](https://user-images.githubusercontent.com/17465487/102215237-65845800-3f14-11eb-9890-861a7e0ce800.png)
> 计算出 x 坐标之间的距离。
> ![图片](https://user-images.githubusercontent.com/17465487/102215386-98c6e700-3f14-11eb-80b1-ddadb7db792d.png)

你好，我也遇到了与你相似的问题，我直接使用conv-social-pool文章的code代码生成训练数据，但是我发现必须将原论文里的max_num_object设置的足够大（我设置的是240）才能够保证在运行data_process.py时不报错，GRIP++模型的其他内容均未修改，但是最终的测试结果与论文的结果相差较大，我的结果大概是Prediction Horizon (s)为1,2,3,4,5的时候，RMSE值2.3、5.5、8.9、13、19。我很疑惑是哪里出现了问题？？？

**Comment by xincoder** [comment]
@guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。 
因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
祝好~

**Comment by ShqWW** [comment]
> @guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
> 
> 1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
> 2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。
>    因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
>    祝好~

好的 我的问题已经解决，暂时不需要你那部分代码了。非常感谢你的回复。

**Comment by guoyage** [comment]
> > @guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
> > 
> > 1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
> > 2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。
> >    因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
> >    祝好~
> 
> 好的 我的问题已经解决，暂时不需要你那部分代码了。非常感谢你的回复。

您好，我想请教一下对于NGSIM数据集的处理，您是怎么做的？？我目前还是没有解决遇到的问题。如果您能够提供帮助，我将非常感谢。

**Comment by ShqWW** [comment]
> > > @guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
> > > 
> > > 1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
> > > 2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。
> > >    因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
> > >    祝好~
> > 
> > 
> > 好的 我的问题已经解决，暂时不需要你那部分代码了。非常感谢你的回复。
> 
> 您好，我想请教一下对于NGSIM数据集的处理，您是怎么做的？？我目前还是没有解决遇到的问题。如果您能够提供帮助，我将非常感谢。

目前我处理数据的方式和新模型是绑定的，等我整理完善之后会考虑将新模型代码以及数据集处理代码开源的。

**Comment by Patrickyc** [comment]
@ShengqiWang 可以将您处理NGSIM的数据集的代码发我一下吗？ 13997826632@163.com  也没能解决NGSIM的数据问题。

**Comment by Xiejc97** [comment]
@ShengqiWang 

> > > > @guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
> > > > 
> > > > 1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
> > > > 2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。
> > > >    因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
> > > >    祝好~
> > > 
> > > 
> > > 好的 我的问题已经解决，暂时不需要你那部分代码了。非常感谢你的回复。
> > 
> > 
> > 您好，我想请教一下对于NGSIM数据集的处理，您是怎么做的？？我目前还是没有解决遇到的问题。如果您能够提供帮助，我将非常感谢。
> 
> 目前我处理数据的方式和新模型是绑定的，等我整理完善之后会考虑将新模型代码以及数据集处理代码开源的。

你好！请问你处理NGSIM数据集并且加载到模型中是如何实现的呢？如果方便的话，可以把相关代码发给我吗jincanxie@163.com？非常感谢你！

**Comment by Yuaneen** [comment]
@ShengqiWang @guoyage @Patrickyc 关于NGSIM数据集处理的代码如果有能发我一份吗，我目前也遇到问题，谢谢！

**Comment by Yuaneen** [comment]
> 

我的邮箱 [wenyuan_echo@126.com](url)

**Comment by Yuaneen** [comment]
> @ShengqiWang @guoyage @Patrickyc 关于NGSIM数据集处理的代码如果有能发我一份吗，我目前也遇到问题，谢谢！

我的邮箱 [wenyuan_echo@126.com](https://github.com/xincoder/GRIP/issues/url)

**Comment by Petrichor625** [comment]
@ShengqiWang  Thanks for your answer and if possible,
 could you please also send me a copy of your code for processing the NGSIM dataset? 
This is very important to us.  Thank you very much for your help! 
(My email is haichengliao_625@foxmail.com)

**Comment by Alreall** [comment]
> > @guoyage @ShengqiWang 非常感谢你们在这里讨论文章细节。我最近一直在travel，回复不及时，望见谅。关于NGSIM数据集，有两点值得强调一下：
> > 
> > 1. 在使用conv-social-pool文章的code生成训练数据之后，我并没有使用data_process.py，而是直接修改了data_loader从而加载处理好的数据。
> > 2. 在NGSIM数据集上训练模型，印象中我训练了200+epochs才停的。
> >    因为最近几个月在travel，远程的服务器在travel前让我关闭了，非常抱歉暂时不能提供NGSIM的code。
> >    祝好~
> 
> 好的 我的问题已经解决，暂时不需要你那部分代码了。非常感谢你的回复。
你好！请问你处理NGSIM数据集并且加载到模型中是如何实现的呢？如果方便的话，可以把相关代码发给我吗[jincanxie@163.com](lizhao128023@163.com)？非常感谢你！

**Comment by lalalabigsun** [comment]
> 1. 而是直接修改了data_loader从而加载处理好的数据

具体在data_loader 中修改的内容是什么，方便告诉一下吗

**Comment by Frankxstt** [comment]
@Patrickyc @guoyage @ShqWW 关于NGSIM数据集处理的代码也能发我一份吗？十分感谢！我的邮箱是xiushi.feng2021@gmail.com
