### ISSUE TITLE
Where is the implementation of trainable graph?

### ISSUE THREAD

**Issue by youngsend** [xincoder/GRIP#15]
Hi, @xincoder , thank you for the code!
Could you tell me where the implementation of trainable graph is? I read code, but didn't find them.
Maybe `edge_importance` is the trainable graph part, but I'm not sure.

**Comment by xincoder** [comment]
@youngsend Yes, you are right. The self.edge_importance is the trainable graph and the pra_A [line75 in model.py] is the fixed graph calculated outside of the model.

**Comment by youngsend** [comment]
@xincoder Thank you for the reply! 
However, I still cannot understand why `importance` is `trainable`. Could you explain it to me?
In `model.py`, It seems that `x, _ = gcn(x, pra_A + importance)` does not update `importance`.

**Comment by xincoder** [comment]
@youngsend Why do you say the "importance" is not updated? The "importance" is initialized as type nn.Parameter (all-ones), in model.py [line 35]. Based on the PyTorch document, the default value of the "requires_grad" property of the nn.Parameter is True, which means the self.edge_importance is automatically added to the list of the model's parameters and is trainable.

**Comment by youngsend** [comment]
@xincoder Thanks for the explanation! Sorry that I'm new to PyTorch...
I see. So `importance` is part of model parameters and is fixed after training. I thought this dynamic graph is dynamic based on input scenarios (while, the fixed graph has always been based on input scenarios). Thanks for your time!

**Comment by xincoder** [comment]
@youngsend , no worries. Yes, you are right. Now, your understanding is correct. The fixed graph is calculated based on the input data, while the trainable graph is tuned while training and is frozen while inference.
