### ISSUE TITLE
论文的网络结构和代码有点不同？

### ISSUE THREAD

**Issue by FCKOP** [xincoder/GRIP#21]
您好，有幸阅读到您的文章（GRIP++）。根据您提供的代码，有3处疑惑，希望您能在百忙之中提供一些帮助，谢谢!
问题1：
论文中Graph Convolutional Model，Graph Operation的处理没有包含卷积操作，直接将上一层的输出作为输入；而代码中Graph Operation前面都是加了一个卷积操作，也就是说每个小block由Graph Operation+BN+CN+BN，变成CN+Graph Operation+BN+CN+BN。不知道是不是我看的不仔细？
问题2 ：
代码中test_model时，是不是没有将预测的RMSE计算步骤的代码实现，结果只有预测的坐标
问题3：
训练中验证的指标，结果大致如[WS] All_All: 0.261 0.475 0.710 0.957 1.200 1.493 5.096和[Test_Epoch161] All_All: 0.257 0.460 0.685 0.935 1.187 1.477 5.001
每个数值代表的是什么指标？是预测的每帧对应的ADE吗？

**Comment by xincoder** [comment]
@FCKOP 非常感谢您对我们文章的关注。
问题1：
	不好意思，我并没有完全理解您提的这个问题。为什么说在论文中没有包含卷积操作？
	首先，GRIP++的Figure1中已经标明BN，Conv2D，GraphOperation，Temporal Conv2D等操作。
	另外，在正文"Graph Convolution Model"部分(第4页，左栏)，第一段提到"the Graph Convolutional Model first passes it through a 2D Convolutional layer with (1×1) kernel size (“Conv2D (1x1)” in Figure 1)"，第二段中"Thus, as shown in Figure 1 (3 Graph Operation layers and 3 Temporal Convolution layers are illustrated)"。
	所以，非常抱歉，我不确定我完全理解了您的这个问题。

问题2 ：
	代码是针对Baidu Apollo Trajectory数据集的。关于这个数据集我们并不能获取到他们测试集的Ground Truth，因此训练完模型，我们需要把预测的结果(坐标)上传到他们的网站得到测试集上ADE/FDE的结果。代码中近似实现了RMSE(main.py line113 compute_RMSE)，没有完全按照RMSE公式进行实现有两方面的原因：(1)为了在模型训练过程中保证数值稳定性，(2)最终的测试结果需要上传到ApolloScape数据集官网进行测试。如果需要得到RMSE的结果，在模型训练结束后，按照公式稍微修改一下compute_RMSE函数，offline算一次即可得到。

问题3：
	WS是weighted sum的缩写，实现在(main.py line254)。这个(0.20, 0.58, 0.22)比例是官网在计算WS时候使用的。详情请参见数据集官网"Metric formula"部分。
	关于每个数值的意义：一共有7个数。前六个是预测出来的每帧的平均误差，最后一个是前六个数字之和。

希望解答了您的问题。

**Comment by FCKOP** [comment]
十分感谢您的回答！很抱歉，没能及时答复！
针对问题一：我的意思是在GraphOperation时，即将输入和fixed graph结合时，代码中用了卷积层。即ConvTemporalGraphical中用了卷积层，可论文中好像没有提及。
另外还想请教一下：论文中WSADE=1.2588和WSFDE=2.3631的结果是在什么参数下实现的？我将代码下载直接运行后epoch=50或者epoch=100时都为1.35左右。

**Comment by xincoder** [comment]
@FCKOP 您是说在graph_operation_layer.py中的self.conv(x)? 如果您是指这个操作，确实我们在文中没有提及，跟relu和dropout操作一样，因为这些部分并不是我们提出方法的主要部分。因为文章篇幅原因，我们没有把模型的每一个layer都进行详细的介绍。我们open source代码也是为了能够尽可能补充文章没有涉及到的细节。

在ReadMe中，提到了1.2588的结果是combine的结果。"We use the following way to combine multiple results." 
使用TitanXP，应该是可以完全复现结果的(当然配置的开发环境会有稍微影响)。使用其他类型的GPU，运行的结果会有些许的不同，这跟GPU的运算精度、模型初始化(虽然code中已经fix住了random seed)。

**Comment by FCKOP** [comment]
十分感谢您的解答，了解了！
但是这个结果的combine的方式是否存在不合理性？这相当于目标检测任务中，把每个类别在不同epoch中的最好结果挑出来，再进行mean IOU的计算了？

**Comment by xincoder** [comment]
@FCKOP 其实会有更好的combine的方式，比如说分别针对不同类型的物体训练一个模型，然后把他们combine在一起。我这样做主要是当时没有足够的时间进行更多的实验+这样简单的combine已经取得比较好的结果(在我提交结果的时候)，所以就没有继续探索了。 做模型combination主要是基于在真实的自动驾驶场景下，也会使用多个模型进行combine。

**Comment by FCKOP** [comment]
明白！感谢您的所有解答！
祝大佬生活愉快，一切顺利！！

**Comment by xincoder** [comment]
@FCKOP 过奖了。再次感谢您对我们工作的关注，祝好~
