### ISSUE TITLE
RuntimeError: cuDNN error

### ISSUE THREAD

**Issue by DashStone** [xincoder/GRIP#23]
Thanks for your great work.

I'm facing a problem when I run the main.py.

```
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/DRL/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 176, in flatten_parameters
    self.batch_first, bool(self.bidirectional))  # type: ignore
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
python-BaseException
```
Can you give me some suggestions?
Thanks a lot!

**Comment by xincoder** [comment]
Hi @DashStone, it seems like your CUDNN does not work properly. The path you provide here shows that you are using Anaconda. In this case, I recommend you install the CUDA toolkit and CUDNN within a new environment (using "conda" commands) and be careful about the version of both CUDA and CUDNN to be compatible with your Nvidia Driver.

**Comment by DashStone** [comment]
> Hi @DashStone, it seems like your CUDNN does not work properly. The path you provide here shows that you are using Anaconda. In this case, I recommend you install the CUDA toolkit and CUDNN within a new environment (using "conda" commands) and be careful about the version of both CUDA and CUDNN to be compatible with your Nvidia Driver.

I update my pytorch version and fix zhe problem. Thank you!

**Comment by xincoder** [comment]
@DashStone Glad to hear that you fixed the problem. Hope you enjoy playing our code. ;-)
