### ISSUE TITLE
Is grip++using heading?

### ISSUE THREAD

**Issue by han1222** [xincoder/GRIP#28]
I watched your code.
I understood that you parsed heading value in your code.  but I think you don't use heading value to predict result.
Is grip++using heading?

**Comment by xincoder** [comment]
Hi @han1222, thank you for your interest in our work. The default GRIP++ uses heading information. If you want to define the input features, please feel free to modify the code [main.py line 94] where the dimensions are chosen.

**Comment by han1222** [comment]
Thank you for your answer and awesome work.
I understood you getting the heading information index 9 from line 94, and after that, can you tell where the heading is being considered in code level?   if I've missed anything letting me know. thank you in advance

**Comment by xincoder** [comment]
@han1222, there is no special design for the model architecture to process heading information. I just feed 4-dimensional data as an input to the model (in_channels=4, main.py line 352). The model is trained to consider the heading information implicitly.

**Comment by han1222** [comment]
Thank you I got it !
