### ISSUE TITLE
velocity input 

### ISSUE THREAD

**Issue by han1222** [xincoder/GRIP#29]
1. 
I read  grip++ takes velocity as input.

I am trying to test your algorithm on real vehicle.

should I conversion traffic object's position to velocity ?

or automatically changed in your code??

If I take input from real time tracking data,  Are there any things to consider?

2. If I change max_num_object = 120 # maximum number of observed objects is 70 in data_process.py

when set  8

Generating Training Data.
Traceback (most recent call last):
  File "data_process.py", line 193, in <module>
    generate_data(train_file_path_list, pra_is_train=True)
  File "data_process.py", line 164, in generate_data
    now_data, now_adjacency, now_mean_xy = generate_train_data(file_path)
  File "data_process.py", line 116, in generate_train_data
    object_frame_feature, neighbor_matrix, mean_xy = process_data(now_dict, start_ind, end_ind, observed_last)
  File "data_process.py", line 66, in process_data
    neighbor_matrix[:num_visible_object, :num_visible_object] = (dist_xy<neighbor_distance).astype(int)
ValueError: could not broadcast input array from shape (13,13) into shape (6,6)

when set  70

Generating Training Data.
Traceback (most recent call last):
  File "data_process.py", line 193, in <module>
    generate_data(train_file_path_list, pra_is_train=True)
  File "data_process.py", line 164, in generate_data
    now_data, now_adjacency, now_mean_xy = generate_train_data(file_path)
  File "data_process.py", line 116, in generate_train_data
    object_frame_feature, neighbor_matrix, mean_xy = process_data(now_dict, start_ind, end_ind, observed_last)
  File "data_process.py", line 91, in process_data
    object_frame_feature[:num_visible_object+num_non_visible_object] = np.transpose(object_feature_list, (1,0,2))
ValueError: could not broadcast input array from shape (73,12,11) into shape (70,12,11)

how can I solve this problem?

**Comment by xincoder** [comment]
@han1222 Thank you for your interest in our work and for trying it on the real vehicle. 

1.
We reported a detailed ablation study in GRIP++ (TABLE III).
From the reported results, you may get some sense of the contribution of each part of our model. 
Then, you can make appropriate modifications based on your hardware limitation or other requirements. 

About the velocity input, I implemented it outside of the model. 
Specifically, in my released code, velocity is calculated in function "preprocess_data" [line 99, main.py].

If the input data is tracking the result, then the performance may be worse than GT. 
It highly depends on the performance of your tracking algorithm. 

2. 
In this case, you may want to modify the code [line 87, data_process.py] to the following:
object_frame_feature[:np.min(num_visible_object+num_non_visible_object, max_num_object)] = np.transpose(object_feature_list, (1,0,2))[:np.min(num_visible_object+num_non_visible_object, max_num_object)]

**Comment by han1222** [comment]
Thank you for your help.
