### ISSUE TITLE
In data_process.py line 15

### ISSUE THREAD

**Issue by han1222** [xincoder/GRIP#30]
"max_num_object = 120 # maximum number of observed objects is 70"

you annotated  max_num_object is 70 In data_process.py line 15
why did you set max_num_object is 120? 

Thank you.

**Comment by xincoder** [comment]
Hi @han1222, thank you so much for your interest in our work. The released GRIP++ code is for the Apolloscape dataset. This dataset contains urban scenarios in which more objects are observed. Thus, I set max_num_object to 120 (after analyzing the training data).

**Comment by han1222** [comment]
Thank you for your quick reply.
