### ISSUE TITLE
Question regarding input dimensions during traning/inference

### ISSUE THREAD

**Issue by DataDemystifier** [xincoder/GRIP#4]
Hey,

thanks for sharing your code! 
I am soon going to try it our but while reading your paper, I wondered how you handle varying sizes of vehicles in the traffic scene.
Your paper always uses n vehicles. However, this cannot be true for all traffic situations that you encounter in the datasets.
Same questions goes for the interactions graphs. Don't you need fixed graph dimensions with fixed number of nodes at least to have a fixed adjacency matrix dimension (for the neighbor graphs).

Looking forward to your answer!

Cheers

**Comment by xincoder** [comment]
@DunkDream First, thank you for your interest in our work. 

You are right, during training and inference, the model should be fixed. This is the reason why I choose a fixed number (maximum number) of objects in a scene. 

To handle the varying numbers of objects, we add a mark to label the data is valid or not. 
	1. **Data Processing**: [line75 in data_process.py] we add an extra dimension to indicate if the current feature is valid. Besides, we add zero-padding if the number of current objects is less than the chosen fixed number, which means valid objects first, then zero-padded objects. 
	2. **Data Loader**: because we have processed the data in step1, thus the loaded data has already included such a mark. [line60 in xin_feeder_baidu.py]
	3. **Training**: [line99 and line113-120 in main.py] we show how we use a mask to handle the data and compute the loss. **Inference**: [line304 in main.py] we get the number of valid objects, and then only select the valid objects [line307 in main.py].

I added comments before sharing the code. Thus, it should be easy for you to understand once you read through my code. You can also simply check the code highlighted above to just get a sense of how I handle the problem you asked. 

Thanks.
