### ISSUE TITLE
固定矩阵和训练矩阵

### ISSUE THREAD

**Issue by Patrickyc** [xincoder/GRIP#5]
您好，有幸阅读您的文章，下面有两个问题希望您能在百忙之中提供帮助。
问题1：请问您文章中固定矩阵和训练矩阵来解决动态的车辆交互问题，在代码中如何体现的呢?
问题2 ：文章中使用平均速度来预测最后的位置信息在代码中是如何体现的呢？

**Comment by xincoder** [comment]
@Patrickyc 首先，非常感谢您对我们工作的关注。

问题1：
	固定矩阵：从dataloader传入到模型中的 (model.py line67, pra_A)。具体计算是在数据预处理过程中已经完成了(data_process.py line 58-62)。
	训练矩阵：在模型结构的一部分，定义在 (model.py line32-38)。 
	固定矩阵和训练矩阵在模型结构上进行element-wise sum操作 (model.py, line75)。

问题2：
	关于这个问题，如果我没理解错的话，您是在问文中提到用Velocity作为输入是吧？
	Velocity的计算实现在 (main.py line98-100)。简单的计算了两帧的位置差，这里使用了一个mask来记录有效帧，减完之后mask掉无效的。 

希望我的回答能帮助您更好的理解我们的工作，同时也希望对您的工作有所启发。

**Comment by Patrickyc** [comment]
真诚感谢您的回复，这几天无法登陆github。
问题一：您在文章中解决车辆动态变化问题上使用的训练矩阵，能了解到的是通过测试的结果表格得知的，在原理上为什么能在提高预测的效果呢，可以告知下您的思路吗？
问题二： 训练矩阵与固定矩阵为何是选择相加而不是相乘呢？ 
问题三：论文中您是打算将得出的预测位置信息与规划结合起来，对您这个想法感兴趣，您能给点启发吗？

**Comment by moriartyjack0520** [comment]
> @Patrickyc 首先，非常感谢您对我们工作的关注。
> 
> 问题1：
> 固定矩阵：从dataloader传入到模型中的 (model.py line67, pra_A)。具体计算是在数据预处理过程中已经完成了(data_process.py line 58-62)。
> 训练矩阵：在模型结构的一部分，定义在 (model.py line32-38)。
> 固定矩阵和训练矩阵在模型结构上进行element-wise sum操作 (model.py, line75)。
> 
> 问题2：
> 关于这个问题，如果我没理解错的话，您是在问文中提到用Velocity作为输入是吧？
> Velocity的计算实现在 (main.py line98-100)。简单的计算了两帧的位置差，这里使用了一个mask来记录有效帧，减完之后mask掉无效的。
> 
> 希望我的回答能帮助您更好的理解我们的工作，同时也希望对您的工作有所启发。

您好！很感谢您的分享！对于您上面问题2的解释，我有个疑问：就是在预测结果predicted处理（model.py line 288~289），这一步是怎么理解呢？谢谢

**Comment by xincoder** [comment]
@moriartyjack0520 我们在数据预处理的时候(main.py line99)做了连续两帧相减的操作，所以输入到模型的数据只是相邻两帧间的位移。因此，在模型预测的时候，我们把每一帧的预测结果(预测出来的也是相邻两帧的位移)累加，从而得到每一帧相对于第一帧的位移。然后在line290，转换成具体的位置坐标。

**Comment by moriartyjack0520** [comment]
> @moriartyjack0520 我们在数据预处理的时候(main.py line99)做了连续两帧相减的操作，所以输入到模型的数据只是相邻两帧间的位移。因此，在模型预测的时候，我们把每一帧的预测结果(预测出来的也是相邻两帧的位移)累加，从而得到每一帧相对于第一帧的位移。然后在line290，转换成具体的位置坐标。

谢谢您的回答！
我这边还有一个问题想请教：model.py的42--44行，您建立了3个一样的Seq2Seq，然后在85--94行的前向计算预测结果取调用它们，我不明白为什么要建立三个一模一样的（我运行之后看了预测的结果，也是很接近）？如果我只是做车辆预测，那么我是否可以在训练的时候只建立一个，然后在测试的时候就只用一个呢？
希望能收到您的回答，谢谢！

**Comment by xincoder** [comment]
@moriartyjack0520 , 非常感谢您对我们工作的持续关注。
1. 为什么使用多个一模一样的模型。
原因一：多个模型正确率有提高。虽然模型结构很相近，但是训练出来的weights会有所差别(哪怕是很小的差别)。我们GRIP++文章(https://arxiv.org/pdf/1907.07792.pdf)Table III报告了相应的结果。
原因二：选择三个模型的直觉在于ApolloScape数据集中包含三种不同类型的物体，我们用三个模型对应三种物体。
原因三：理论证明网络越宽(不一定需要一模一样的网络结构)，在训练时候越容易达到全局最优(http://proceedings.mlr.press/v89/zhang19d.html).
2. 如果只做车辆预测，可以只用一个。但是用多个并行的模型的正确率可能会高一点(需要实验验证)。原因三中提到，理论上证明模型越宽在训练时越容易达到全局最优(但是理论没有证明这种网络的泛化能力，所以针对不同的数据集，测试的结果可能会有所差别)。
