### ISSUE TITLE
error about the display_result() function

### ISSUE THREAD

**Issue by tlqqidong** [xincoder/GRIP#6]
Hello,

Thank you for your great job. I am confused about the **display_result()** function in main.py. The function seems to have some errors in calculating the RMSE loss which computes the RMSE loss as follows:

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal&space;RMSE&space;=&space;\frac{1}{n}&space;\sqrt{\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal&space;RMSE&space;=&space;\frac{1}{n}&space;\sqrt{\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" title="\mathcal RMSE = \frac{1}{n} \sqrt{\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" /></a>

rather than as the Eq. (10) in the paper of GRIP++:

<a href="https://www.codecogs.com/eqnedit.php?latex=\mathcal&space;RMSE&space;=&space;\sqrt{\frac{1}{n}\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" target="_blank"><img src="https://latex.codecogs.com/gif.latex?\mathcal&space;RMSE&space;=&space;\sqrt{\frac{1}{n}\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" title="\mathcal RMSE = \sqrt{\frac{1}{n}\sum_{i=1}^{n}(Y_{pred}^{t}[i]-Y_{GT}^{t}[i])^{2}}" /></a>

**Comment by xincoder** [comment]
Hi @asddddyyyy , first thank you for your interest in our work. You are right, the implementation of this function calculates the equation you mentioned above. Computing "sqrt" in the denominator has numerical stability problem, thus, in the released code, we only use it to monitor the training and validation performance of the model. The implementation does not impact the testing results. If we want to get the results on the testing set, we have to submit the predicted results to the Baidu Apolloscape website.

**Comment by tlqqidong** [comment]
Many thanks for your prompt reply. The information is very useful to me.
