### ISSUE TITLE
真诚感谢您的回复。

### ISSUE THREAD

**Issue by Patrickyc** [xincoder/GRIP#7]
再次仔细阅读您文章后：有以下问题
问题一：您在文章中解决车辆动态变化问题上使用的训练矩阵，是通过测试的结果表格得知能改善预测的效果，在原理上为什么能提高预测的效果呢，可以告知下您的思路吗？
问题二： 如果训练矩阵训练出来的参数与固定矩阵为何是选择相加而不是相乘呢？ 
问题三：论文中您未来是打算将得出的预测位置信息与车辆规划结合起来，对您这个想法感兴趣，您能给点启发吗，如何相结合呢？

**Comment by xincoder** [comment]
@Patrickyc 非常感谢您对我们工作的关注。
问题一：在模型设计的时候，我希望能够通过一种方式来直接表示车辆之间的影响关系，经过调研之后感觉图卷积是个不错的选择。但是，最初使用的图卷积的矩阵是固定的，也就是车辆之间的影响程度是提前人为设计好的，这样的设计在实际应用中可能并不能很好的适应场景的变化，所以后来加了一个可训练的矩阵。最终的目的还是希望能够用一个比较好的方式来表示车辆之间的影响关系（应该有不同的权重）。有了这样的表示，车辆跟车辆之间的影响，通过图卷积感受野的扩大（层数越多感受野越大）而逐渐传递。所以，经过图卷积网络之后，临近的车辆受到的影响比较大，远处的车辆也会受到影响，之后影响程度低一些，这也比较符合自动驾驶场景下的实际情况，也与直觉相符。
问题二：结合问题一的回答，固定矩阵从直觉上来看，设计是没有问题的。但是固定矩阵在适应场景变化方面表现不是很理想，所以使用与可训练的矩阵相加来进行微调。这样，可训练矩阵是作为固定矩阵的残差来进行训练的，数值的变化范围会更集中一些，更容易训练。
问题三：这是一个开放性的问题。在对ego车辆进行路径规划的时候，需要用到周围车辆的历史轨迹和预测的未来轨迹。有了周围车辆未来轨迹的预测结果，ego车辆路径规划的时候可以做出一定的避让（如加速、减速、改变轨迹等）。
