### ISSUE TITLE
O.o简单的问题o.O

### ISSUE THREAD

**Issue by chaosles** [xincoder/GRIP#8]
我有一个简单的问题，关于输入数据的深度的，也就是main.py中Model的in_channels为什么是4呢。是指的[position_x, position_y，heading] + [mask]，这四个特征吗。
如果我扩充每个对象的特征到6个，是应该设置in_channels=6吗？

感谢您的回答，对此我有点迷惑。

**Comment by xincoder** [comment]
@chaosles 非常感谢您对我们工作的关注。你的理解是对的，在main.py [line94]，我指定了选择的特征。现在开源的这个代码只使用了[position_x, position_y, heading] 三个特征，以及[mask]用来标识是否是有效特征，所以一共是4维，故in_channels=4。如果你使用更多的特征，可以在main.py [line94] 进行相应的修改，同时将in_channels设置成对应数值。PS:值得注意的是，我在做预处理的时候是根据选择的这四维特征进行处理（如main.py line98-100），因此，如果您想增加或者减少特征维数，请注意对应的索引（可能会涉及到多处代码）。

**Comment by chaosles** [comment]
> @chaosles 非常感谢您对我们工作的关注。你的理解是对的，在main.py [line94]，我指定了选择的特征。现在开源的这个代码只使用了[position_x, position_y, heading] 三个特征，以及[mask]用来标识是否是有效特征，所以一共是4维，故in_channels=4。如果你使用更多的特征，可以在main.py [line94] 进行相应的修改，同时将in_channels设置成对应数值。PS:值得注意的是，我在做预处理的时候是根据选择的这四维特征进行处理（如main.py line98-100），因此，如果您想增加或者减少特征维数，请注意对应的索引（可能会涉及到多处代码）。

谢谢您的提醒，我注意到有多处mask对应索引需要修改
